import { LibrarianSession, LibraryTenant, TenantBook, TenantLoan } from '@/types/tenant';

export const mockLibraries: LibraryTenant[] = [
  {
    id: 'lib-honduras',
    name: 'Honduras City Library',
    subdomain: 'honduras',
    city: 'Tegucigalpa',
    accent: '#c76832',
    description: 'A community-focused catalog for civic reading rooms and school partnerships.',
  },
  {
    id: 'lib-newyork',
    name: 'New York Reading House',
    subdomain: 'newyork',
    city: 'New York',
    accent: '#17594a',
    description: 'A neighborhood-driven branch network with quick pickup and returns.',
  },
];

export const mockBooks: TenantBook[] = [
  {
    id: 'book-1',
    library_id: 'lib-honduras',
    title: 'The House on Mango Street',
    author: 'Sandra Cisneros',
    categories: ['fiction'],
    total_copies: 8,
    available_copies: 5,
    library_codes: ['honduras0001', 'honduras0002', 'honduras0003', 'honduras0004', 'honduras0005', 'honduras0006', 'honduras0007', 'honduras0008'],
    book_code: 'MC-001',
    editorial: 'Vintage',
    edition: '25th Anniversary',
    cover_type: 'softcover',
    shelf_location: 'A-12',
    cost: 15.99,
    acquired_at: '2023-01-15',
    image_url: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1461352425i/139253.jpg',
    archived_at: null,
  },
  {
    id: 'book-2',
    library_id: 'lib-honduras',
    title: 'Atomic Habits',
    author: 'James Clear',
    categories: ['self-improvement', 'psychology'],
    total_copies: 6,
    available_copies: 2,
    library_codes: ['honduras0009', 'honduras0010', 'honduras0011', 'honduras0012', 'honduras0013', 'honduras0014'],
    book_code: 'AH-99',
    editorial: 'Penguin',
    edition: '1st',
    cover_type: 'hardcover',
    shelf_location: 'B-04',
    cost: 24.50,
    acquired_at: '2023-05-20',
    image_url: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg',
    archived_at: null,
  },
  {
    id: 'book-3',
    library_id: 'lib-honduras',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    categories: ['science', 'physics'],
    total_copies: 4,
    available_copies: 1,
    library_codes: ['honduras0015', 'honduras0016', 'honduras0017', 'honduras0018'],
    book_code: 'SH-01',
    editorial: 'Bantam',
    edition: 'Updated',
    cover_type: 'softcover',
    shelf_location: 'S-01',
    cost: 18.00,
    acquired_at: '2022-11-10',
    image_url: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1333578746i/3869.jpg',
    archived_at: null,
  },
  {
    id: 'book-4',
    library_id: 'lib-newyork',
    title: 'Beloved',
    author: 'Toni Morrison',
    categories: ['literature', 'fiction'],
    total_copies: 7,
    available_copies: 4,
    library_codes: ['newyork0001', 'newyork0002', 'newyork0003', 'newyork0004', 'newyork0005', 'newyork0006', 'newyork0007'],
    book_code: 'TM-B0',
    editorial: 'Alfred A. Knopf',
    edition: '1st',
    cover_type: 'hardcover',
    shelf_location: 'L-05',
    cost: 22.00,
    acquired_at: '2023-03-12',
    image_url: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1632283723i/6149.jpg',
    archived_at: null,
  },
  {
    id: 'book-5',
    library_id: 'lib-newyork',
    title: 'Educated',
    author: 'Tara Westover',
    categories: ['memoir', 'biography'],
    total_copies: 5,
    available_copies: 3,
    library_codes: ['newyork0008', 'newyork0009', 'newyork0010', 'newyork0011', 'newyork0012'],
    book_code: 'TW-01',
    editorial: 'Random House',
    edition: '1st',
    cover_type: 'softcover',
    shelf_location: 'M-10',
    cost: 16.50,
    acquired_at: '2023-08-05',
    image_url: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506041219i/35133922.jpg',
    archived_at: null,
  },
];


export const mockLibrarians: LibrarianSession[] = [
  {
    id: 'librarian-1',
    email: 'ana@librarian.test',
    full_name: 'Ana Rivera',
    library_ids: ['lib-honduras'],
  },
  {
    id: 'librarian-2',
    email: 'marcus@librarian.test',
    full_name: 'Marcus Green',
    library_ids: ['lib-honduras', 'lib-newyork'],
  },
];

export const mockLoans: TenantLoan[] = [
  {
    id: 'loan-1',
    library_id: 'lib-honduras',
    book_id: 'book-1',
    full_name: 'Luis Hernandez',
    identifier: 'luis@example.com',
    requested_copies: 1,
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'loan-2',
    library_id: 'lib-honduras',
    book_id: 'book-2',
    full_name: 'Luis Hernandez',
    identifier: 'luis@example.com',
    requested_copies: 1,
    status: 'handled',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    handled_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    id: 'loan-3',
    library_id: 'lib-newyork',
    book_id: 'book-4',
    full_name: 'Maya Brooks',
    identifier: 'student-88',
    requested_copies: 1,
    status: 'approved',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];
